### ISSUE TITLE
Basic Vocabulary

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/userStories#1]
## Value Proposition

**As a** user

**I need** to see a collection of flash cards with word pairs in english as well as
the query language,

**to be able to** review and practice them.

## Description

![image](https://user-images.githubusercontent.com/115288914/206714714-267f37f9-b607-4c21-bc5e-575f5578ede2.png)

## Acceptance Criteria

- [ ] Cards with word pairs are rendered in a flexible design (grid 2 equal columns)
- [ ] window content is scrollable (vertically)
- [ ] margin is the same for every card
- [ ] card size according to text content (height/width auto)

## Tasks

- [ ] branch
- [ ] write basic vocab data in dummy array
- [ ] render basic vocab as cards using components
- [ ] storybook
- [ ] testing

**Comment by ufelgen** [comment]
> Hey Ully, ich würde die Sprache noch konkretisieren. 'query language' ist sicher im ersten Schritt eine bestimmte Sprache, schreib das ruhig hin .
> 
> In deinem Scribble gibt es eine Überschrift, aber in den ACs nicht - kannst du defineren was da stehen solll?
> 
> sonst supi :octocat:

Danke Julia, hab ich berücksichtigt :)
