### ISSUE TITLE
Add the gender to the query nouns (US-2)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/userStories#2]
## Value Proposition

**As a** user

**I need** to see the query noun's gender displayed

**to be able to** improve my learning experience

## Description

![image](https://user-images.githubusercontent.com/115288914/206718400-e7b49814-ea49-4d3c-b101-30aba94f502f.png)

## Acceptance Criteria

- [ ] m, f, or n is displayed next to each noun of the query language

## Tasks

- [ ] work on a branch
- [ ] create a new element next to the query language nouns
- [ ] this element accesses an additional property of the dummy data array, where the gender is stored
- [ ] storybook/ testing

**Comment by marvinRoellecke** [comment]
nicely simple user stories, easy to review. :)
