### ISSUE TITLE
add categories (US-3)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/userStories#3]
## Value Proposition

**As a** user

**I want to** structure my vocab in different categories

**to be able to** keep track of my vocabulary and learn more efficiently

## Description

![image](https://user-images.githubusercontent.com/115288914/206723070-cd27cc3a-e393-4ba8-b4cd-7d1f1c8918d4.png)

## Acceptance Criteria

- [ ] a page is added which displays a category overview (with the category name and the number of words in this category) 
- [ ] when clicked, each category button leads to the vocab list stored under this category name
- [ ] the category page has a navigation element at the bottom, which contains a home button leading back to the category overview page

## Tasks

- [ ] work on a branch 
- [ ] routing: category overview page, dynamic [category] page 
- [ ] access additional arrays in the dummy data for different categories
- [ ] storybook/testing

**Comment by marvinRoellecke** [comment]
well done.
Maybe you can add the task "create nav bar"
