### ISSUE TITLE
Form to add new cards (US-4)

### ISSUE THREAD

**Issue by ufelgen** [ufelgen/userStories#4]
## Value Proposition

**As a** user

**I want to** add my own vocabulary

**to be able to** personalize my learning experience

## Description

![image](https://user-images.githubusercontent.com/115288914/206729794-cfa5f660-bb90-403e-80a6-31b498606c2b.png)

## Acceptance Criteria

- [ ] a form is added on the main page (category overview) with the following elements
- [ ] required text input field for the word in the base language (label: "english" or "base")
- [ ] required text input fields for the word in query language 1: the label is a dropdown menu for different languages and where the last chosen language is pre-selected
- [ ] an optional form field with a dropdown menu ( --empty--, m, f, n) where the user can specify gender if the word is a noun
- [ ] required choose-one form field with a dropdown menu where the user can assign the word to a category (dropdown options: all existing categories and a " + new category" option)
- [ ] a submit button that adds the form data to the correct category

## Tasks

- [ ] work on a branch
- [ ] add a form component as described above
- [ ] storybook/ testing
